### ISSUE TITLE
IWPR Gateway XML files

### ISSUE THREAD

**Issue by larshp** [grahamrobbo/teched16_example#1]
Hi Graham,
I have fixed the dump when pulling IWPR artifacts via abapGit-plugins.

Can you try upgrading abapGit-plugins to latest version and push the changed files? 

Currently I dont have a test system with VBAK in it, so I get a lot of errors and differences.

**Comment by gregorwolf** [comment]
Hi Graham,

with my commits [one](https://github.com/gregorwolf/teched16_example/commit/6aa7fd74309480444f3e6701ed4859f24ad4e2b3) and [two](https://github.com/gregorwolf/teched16_example/commit/6284019457bfe06f88c391e8bc84b88df5005e8e) I can now activate on my NSP system. I've updated abapGit and the plugins but I still get errors  when I try to import:

 IWOM ZDEMO_MDL_0001_BE  
 IWPR ZTECHEDDEMO  
 IWSG ZDEMO_SRV_0001  

When I removed this files from my forked repository I wall able to import all the rest. Let me know what further information you need.

**Comment by grahamrobbo** [comment]
Bugger....I only added these Gateway artifacts after abapGit started supporting them. This will probably be because the GW config data is not included. I think I will remove these from the repo and have people manually register the Gateway service.

Did registering and activating the service work okay? Especially pointing to the subclassed MPC & DPC?

**Comment by larshp** [comment]
I think it will work if you add the Gateway artifacts again, see https://github.com/larshp/abapGit/issues/75

The export of the artifacts worked, but import was recently fixed

**Comment by grahamrobbo** [comment]
Great - is someone ( @gregorwolf ) able to test this for me? ;) All the systems I have access to already have this example setup.

**Comment by larshp** [comment]
@grahamrobbo first you have to upgrade to latest abapgit + plugins and push objects:

IWOM ZDEMO_MDL_0001_BE
IWPR ZTECHEDDEMO
IWSG ZDEMO_SRV_0001

to the repository again

**Comment by gregorwolf** [comment]
I'm happy to test when @grahamrobbo pushed the updated objects.

**Comment by grahamrobbo** [comment]
Please test whenever you can. Thanks

**Comment by larshp** [comment]
Hi Graham,
I did some testing, it fails when importing

IWOM ZDEMO_MDL_0001_BE
(and probably same issue with IWSG ZDEMO_SRV_0001)

the IWOM file in the respository is 2 months old, can you check that the latest version of the file is pushed using latest abapGit and latest abapGit-Plugins?

**Comment by gregorwolf** [comment]
Hi Graham / Lars,

first I'm getting this error:

![IWOM](https://cloud.githubusercontent.com/assets/2639535/19739686/3d00436c-9bbc-11e6-8046-ff39440d197d.png)

I've cloned your repository again and delete the object above. Then I get:

![IWPR](https://cloud.githubusercontent.com/assets/2639535/19739709/52bd4754-9bbc-11e6-82f2-34b3e389f8b3.png)

Deleting thet I get the error:

![IWSG](https://cloud.githubusercontent.com/assets/2639535/19739769/9319782c-9bbc-11e6-8eb9-ee816d1f3f95.png)

Before I've started that I've updated abapGit and the plugins to the latest Git version.

CU
Gregor

**Comment by grahamrobbo** [comment]
I updated to the latest version of abapGit & plugins on my development system. This picked up some additional objects that were missed in the earlier commit.

I have just successfully installed the package on one of my customer's systems - first updating to the latest abapGit & plugins. All objects installed & compiled successfully.

I then maintained the model & services....
![image](https://cloud.githubusercontent.com/assets/1305633/19751285/e0b60a14-9c43-11e6-8ea8-d541a66f9687.png)

...and finally registered the system alias for the service.
![image](https://cloud.githubusercontent.com/assets/1305633/19751319/08de40f6-9c44-11e6-949f-74b9fdd57f1d.png)

All worked fine. The customer system is running NW 7.40 SP 10.

**Comment by gregorwolf** [comment]
Unfortunately I'm still getting:

![IWPR](https://cloud.githubusercontent.com/assets/2639535/19756400/98a1a98a-9c1c-11e6-8930-9c21f4f31916.png)

after removing that file from my fork I was able to import without errors.

I would think you should not include the ICF-Node and the registered Service in the repository. The /IWFND/MAINT_SERVICE should be a manual step as it is also in SAP delivered standard services. 

Using the reports /IWBEP/R_DST_SERVICE_BUILDER and /IWBEP/R_DST_MODEL_BUILDER I was able to define the service and then register in /IWFND/MAINT_SERVICE. And I get results for all entity sets.

**Comment by larshp** [comment]
I get an error when installing on 750(same error as Gregor describes above), opened issue https://github.com/larshp/abapGit-Plugins/issues/13

**Comment by grahamrobbo** [comment]
I'm in two minds about this. It seems that removing the ICF-node & GW Service objects from the repo will get everything to activate on a 750 system. On the other hand if resolving issue [abapGit-Plugins#13](https://github.com/larshp/abapGit-Plugins/issues/13) fixes this it makes the install easier for people with little GW experience.

Do you guys have a preference?
![image](https://cloud.githubusercontent.com/assets/1305633/19786569/5a682472-9cea-11e6-8eb4-a3b493c74600.png)

**Comment by larshp** [comment]
I'll try to do a quick fix of https://github.com/larshp/abapGit-Plugins/issues/13 today

**Comment by larshp** [comment]
I have updated abapGit-Plugins, @gregorwolf try again after updating to latest abapGit-Plugins. It works for me on 750

**Comment by gregorwolf** [comment]
We're getting there. Everything get's activated without issues. 

After installing on 7.40 and 7.50 the first problem that occurs is that the System Alias you're shipping doesn't exist. I would suggest you replace it with LOCAL.

After I've corrected this I've got:

```
<code>/IWBEP/CM_MGW_RT/026</code>
<message xml:lang="en">No service found for namespace /SAP/, name ZDEMO_SRV, version 0001.</message>
```

when calling the service. This I've fixed by executing the reports:

/IWBEP/R_DST_MODEL_BUILDER
/IWBEP/R_DST_SERVICE_BUILDER

To maintain the model and the service. I think when the slide pages 72 and 73 will be mentioned explicitly the novice user should be fine.

**Comment by grahamrobbo** [comment]
Hi @gregorwolf 

Thanks for your help on this. I have modified the documentation to more explicitly talk about how to configure and activate the service.

I am surprised that you see the System Alias is not set to LOCAL. It is on my development system and it also appears to be the case in the repo. Can you check this pls?

``` <_-IWFND_-I_MED_SIN>
     <SRV_IDENTIFIER>ZDEMO_SRV_0001</SRV_IDENTIFIER>
     <IS_ACTIVE>A</IS_ACTIVE>
     <NAME>BEP_SVC_SOURCE_SYSTEM</NAME>
     <VALUE>LOCAL</VALUE>
    </_-IWFND_-I_MED_SIN>
```

**Comment by larshp** [comment]
closing

**Comment by grahamrobbo** [comment]
FYI - in latest release I have removed the GW model, service & ICF objects from the repo. They are not needed as the process of registering and activating the demo service creates them anyway.
