### ISSUE TITLE
User EPM data instead of VBAK

### ISSUE THREAD

**Issue by gregorwolf** [grahamrobbo/teched16_example#3]
Hi Graham,
to allow also an installation of your example on the NetWeaver ABAP Developer Edition it would be the best to replace the VBAK read  with SNWD_SO and SNWD_SO_I? 
Best regards
Gregor

**Comment by larshp** [comment]
I had the same problem, but was thinking perhaps to base the example on SFLIGHT, however I guess it is a lot of work

**Comment by gregorwolf** [comment]
EPM is the way to go. SFLIGHT shouldn't be used anymore.

**Comment by larshp** [comment]
oh, okay :smile:

**Comment by grahamrobbo** [comment]
Okay...have changed demo to work against EPM tables. Merged into master. 

It would be great if someone could test deployment to a clean ABAP stack for me pls?

**Comment by gregorwolf** [comment]
Hi Graham,

while activating I get the error:

Protected section ZCL_DEMO_CUSTOMER
Type "ISI_COUNTRY_HELP_TT" is unknown

Seems ISI_COUNTRY_HELP_TT isn't known in an AS ABAP 7.40.

CU
Gregor

**Comment by grahamrobbo** [comment]
Oops....my bad. Fixed in [this commit](https://github.com/grahamrobbo/teched16_example/commit/6b8f91d6ff2ac8f64a553096db0e93463d070814)
